### PR TITLE
[SHIRO-670] ByteSource Serializable！

### PR DESCRIPTION
**Pull request by ChunMengLu**

### CODE REVIEW

**Comment by fpapon** [comment]
@ChunMengLu can you explain why extend `Serializable` here please?

**Comment by ChunMengLu** [comment]
> can you explain why extend `Serializable` here please?

Password Hash salt，redis Serializable。

**Comment by bdemers** [comment]
Not all implementations of ByteSource can be serializable. For example if the source was an input stream.  That said, it should be easy store marshal/unmarshal to any custom store by just calling `getBytes()` or `toBase64()` 

@ChunMengLu do you have a custom Session Cache?

**Comment by ChunMengLu** [comment]
> do you have a custom Session Cache

Yes，last i use custom ByteSource. （🇨🇳最后我自定义了一个ByteSource实现。）

```java
@Override
protected AuthenticationInfo doGetAuthenticationInfo(

    //......

return new SimpleAuthenticationInfo(shiroUser, user.getPassword().toCharArray(), ShiroByteSource.of(user.getSalt()), getName());
```

Just adding implements Serializable doesn't seem to work. Can you optimize the Session Cache interface to facilitate custom implementation? （ 🇨🇳只添加 implements Serializable 好像是不行的，能否优化一下 Session Cache 接口去方便客户自定义实现。）

**Comment by bdemers** [comment]
@ChunMengLu Lets take a step back.
Are you seeing a unmarshalling  error when reading an object from the cache/session?

**Comment by DR-YangLong** [comment]
你要将shiro的session存入缓存系统，在各个应用之间共享，你需要去重写shiro的session实现，因为shiro当前的session实现序列化/反序列化是通过readObject和writeObject进行的，也就意味着只有支持标准JDK的序列化/反序列化库能够正确的进行session的序列化和反序列化，例如使用kryo时需要单独为shiro配置序列化器为JDK序列化器，或使用fst。 @ChunMengLu

**Comment by fpapon** [comment]
@DR-YangLong can you write in english please?

**Comment by DR-YangLong** [comment]
if you just went share session,look at the interface [Session](https://github.com/apache/shiro/blob/master/core/src/main/java/org/apache/shiro/session/Session.java) and the default implemention [SimpleSession ](https://github.com/apache/shiro/blob/master/core/src/main/java/org/apache/shiro/session/mgt/SimpleSession.java).the default implemention just can use JDK Serializer to serialize/deserialize.

**Comment by ChunMengLu** [comment]
> if you just went share session,look at the interface [Session](https://github.com/apache/shiro/blob/master/core/src/main/java/org/apache/shiro/session/Session.java) and the default implemention [SimpleSession ](https://github.com/apache/shiro/blob/master/core/src/main/java/org/apache/shiro/session/mgt/SimpleSession.java).the default implemention just can use JDK Serializer to serialize/deserialize.

I use EnterpriseCacheSessionDAO and Only the cacheManager was rediscovered。

**Comment by ChunMengLu** [comment]
Two years ago, I was ok after I customized my ShiroByteSource.

**Pull request closed without merging**
