### PR TITLE
Adds BearerToken support

### PR DESCRIPTION
**Pull request by bdemers**
Abstracts the HTTP header processing out of BasicHttpAuthenticationFilter into HttpAuthenticationFilter (to support both BASIC and Bearer tokens)

Adds `authcBearer` to DefaultFilter (to match `authcBasic`)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/71/<h2>Build result: FAILURE</span></h2>[...truncated 228.99 KB...][JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/config/core/target/shiro-config-core-1.5.0-SNAPSHOT-javadoc.jar to org.apache.shiro/shiro-config-core/1.5.0-SNAPSHOT/shiro-config-core-1.5.0-SNAPSHOT-javadoc.jar[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/config/core/target/shiro-config-core-1.5.0-SNAPSHOT-sources.jar to org.apache.shiro/shiro-config-core/1.5.0-SNAPSHOT/shiro-config-core-1.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/test-coverage/pom.xml to org.apache.shiro/shiro-test-coverage/1.5.0-SNAPSHOT/shiro-test-coverage-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/crypto/pom.xml to org.apache.shiro/shiro-crypto/1.5.0-SNAPSHOT/shiro-crypto-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/core/pom.xml to org.apache.shiro/shiro-core/1.5.0-SNAPSHOT/shiro-core-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/samples/aspectj/pom.xml to org.apache.shiro.samples/samples-aspectj/1.5.0-SNAPSHOT/samples-aspectj-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/samples/spring-boot-web/pom.xml to org.apache.shiro.samples/samples-spring-boot-web/1.5.0-SNAPSHOT/samples-spring-boot-web-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/samples/spring-client/pom.xml to org.apache.shiro.samples/samples-spring-client/1.5.0-SNAPSHOT/samples-spring-client-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/tools/hasher/pom.xml to org.apache.shiro.tools/shiro-tools-hasher/1.5.0-SNAPSHOT/shiro-tools-hasher-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/support/spring-boot/spring-boot-starter/pom.xml to org.apache.shiro/shiro-spring-boot-starter/1.5.0-SNAPSHOT/shiro-spring-boot-starter-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/support/jaxrs/pom.xml to org.apache.shiro/shiro-jaxrs/1.5.0-SNAPSHOT/shiro-jaxrs-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/samples/guice/pom.xml to org.apache.shiro.samples/samples-guice/1.5.0-SNAPSHOT/samples-guice-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/crypto/cipher/pom.xml to org.apache.shiro/shiro-crypto-cipher/1.5.0-SNAPSHOT/shiro-crypto-cipher-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/crypto/cipher/target/shiro-crypto-cipher-1.5.0-SNAPSHOT.jar to org.apache.shiro/shiro-crypto-cipher/1.5.0-SNAPSHOT/shiro-crypto-cipher-1.5.0-SNAPSHOT.jar[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/crypto/cipher/target/shiro-crypto-cipher-1.5.0-SNAPSHOT-javadoc.jar to org.apache.shiro/shiro-crypto-cipher/1.5.0-SNAPSHOT/shiro-crypto-cipher-1.5.0-SNAPSHOT-javadoc.jar[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/crypto/cipher/target/shiro-crypto-cipher-1.5.0-SNAPSHOT-sources.jar to org.apache.shiro/shiro-crypto-cipher/1.5.0-SNAPSHOT/shiro-crypto-cipher-1.5.0-SNAPSHOT-sources.jar[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/samples/web/pom.xml to org.apache.shiro.samples/samples-web/1.5.0-SNAPSHOT/samples-web-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/support/servlet-plugin/pom.xml to org.apache.shiro/shiro-servlet-plugin/1.5.0-SNAPSHOT/shiro-servlet-plugin-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/support/spring/pom.xml to org.apache.shiro/shiro-spring/1.5.0-SNAPSHOT/shiro-spring-1.5.0-SNAPSHOT.pom[JENKINS] Archiving /home/jenkins/jenkins-slave/workspace/Shiro-pr/support/guice/pom.xml to org.apache.shiro/shiro-guice/1.5.0-SNAPSHOT/shiro-guice-1.5.0-SNAPSHOT.pomchannel stoppedSetting status of efcbf77d109030c47b0ed8f03fb219b800642117 to FAILURE with url https://builds.apache.org/job/Shiro-pr/71/ and message: 'FAILURE 'Using context: Jenkins: mvn clean install

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/72/

**Comment by bdemers** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/90/

**Comment by fpapon** [comment]
Thanks @bdemers !

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/100/

**Pull request merged**
