### PR TITLE
WIP: SHIRO-417 Allow for basic templating in permission annotation matching parameters

### PR DESCRIPTION
**Pull request by bdemers**
First pass at applying patch attached to SHIRO-417
TODO: Needs a few more unit tests

Moving to a WIP pull request to make sure this messes well with SHIRO-314

### CODE REVIEW

**Comment by hosswald** [comment]
This would be _incredibly_ helpful.

**Comment by fpapon** [comment]
@bdemers I added this one to 2.0.0 ;)

**Comment by bdemers** [comment]
replaced by #185

**Comment by ledahulevogyre** [comment]
I try to implement this in our code. Once I extended PermissionAnnotationMethodInterceptor, how can I inject it so that it replaces the default interceptor ?

(Btw, why is this closed ? Does #185 really allow to use parameters in annotations ?)

Thanks.

**Pull request closed without merging**
