### PR TITLE
[SHIRO-660] Bug in FirstSuccessfulStrategy

### PR DESCRIPTION
**Pull request by lileibuaa**
The '!' lost in the process of migration from 1.3.x to 1.4.0.

### CODE REVIEW

**Comment by lileibuaa** [comment]
```diff
      * since this strategy mandates that only the info from the first successfully authenticated realm be used.
      */
     protected AuthenticationInfo merge(AuthenticationInfo info, AuthenticationInfo aggregate) {
-        if (aggregate != null && isEmpty(aggregate.getPrincipals())) {
+        if (aggregate != null && !isEmpty(aggregate.getPrincipals())) {
             return aggregate;
         }
         return info != null ? info : aggregate;
```

**Comment by bdemers** [comment]
+1 Thanks!!
This looks like it happened in: https://github.com/apache/shiro/commit/0089825463bb6159e36ea29d241a9250a246f01a

We should probably add a test for this though

**Comment by fpapon** [comment]
Hi @bdemers, can we merge this?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/16/

**Comment by bdemers** [comment]
Looks fine to me, my pref is we add a test first, but I'm not going to block it

**Comment by fpapon** [comment]
@bdemers ok you're right for the test.
@lileibuaa can you add a test? If you can't I can deal with it ;)

**Comment by fpapon** [comment]
@bdemers ok you're right for the test.
@lileibuaa can you add a test? If you can't I can deal with it ;)

**Comment by lileibuaa** [comment]
@fpapon Yep， my pleasure!

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/24/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/23/

**Comment by fpapon** [comment]
LGTM, thanks!

**Pull request merged**
