### PR TITLE
[#ISSUE 1005] - Expand checkstyle to all modules (root) 

### LINKED ISSUE #1005: Expand checkstyle to all modules (root)
Currently, only Jakarta EE module has checkstyle enabled.
Need to enable checkstyle on root module, so it encompasses all modules.
Of course, this requires that all modules comply with the checkstyle rules.
This needs to be done as well.

### PR DESCRIPTION
**Pull request by damonxue**
fixes #1005 

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
I had signed an [Individual Contributor License Agreement] in `Apache ShenYu` project.

### CODE REVIEW

**Comment by damonxue** [comment]
It's just manual labor.  But CI is needed.

**Comment by lprimak** [comment]
there are still compiler errors :(

**Comment by damonxue** [comment]
> there are still compiler errors :(

I think the reason is `checkstyle-plugin` in `owasp` profile. I use `mvn checkstyle:check -Powasp` to check the style, There are no compiler errors. So the question is where we should put the `checkstyle-plugin` in.

**Comment by lprimak** [comment]
yea... the code needs to compile has nothing to do with checkstyle. Also owasp is only secure checks, not the code style etc.

**Comment by damonxue** [comment]
> yea... the code needs to compile has nothing to do with checkstyle. Also owasp is only secure checks, not the code style etc.

It's my fault, i did not see the `build plugins`. And did the compile error cause by the property of `root.dir`?

**Comment by lprimak** [comment]
No problem. The point of this issue is to fix Shiro code so it complies with the checkstyle rules and passes.

No, `root.dir` doesn't cause any issues.

**Comment by damonxue** [comment]
@lprimak pls review.

**Comment by damonxue** [comment]
@lprimak pls review.

**Comment by lprimak** [comment]
I ran into some backlog in my day job. Please be patient.

**Comment by lprimak** [comment]
First of all, great job, thanks!
I have fixed up the configuration for the most part to the way it was.

However, some major and  minor issues remain
Some minor issues:
- Line endings. Looks like you have windows line endings in your source code. This repo uses unix line endings. Can you fix that?

Major issues:
- Tests and demos need to be included in checkstyle checking
- There are too many changes in checkstyle configuration. Most things should be done inline using `@SuppressWarnings` and not in configuration

**Comment by lprimak** [comment]
I have started the process to fix code with the new config. Ready for you to take over and finish it. The things I did should get you started.

Thank you once again, great job!

**Comment by lprimak** [comment]
The only configuration that should be modified now is by adding more `JavadocPackage`s in suppressins.xml
Everything else should be made inline unless I missed something egregious

**Comment by damonxue** [comment]
Ok, i see. I will done the unfinished.

**Comment by damonxue** [comment]
@lprimak I formated all file in line endings of `LF`, but the CI with the `windows` system run failed. Pls tell me how to do with the errors.
```
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf"/>
    </module>
```

**Comment by damonxue** [comment]
@lprimak @bmarwell pls review.

**Comment by lprimak** [comment]
You are doing a bit too much...
- Only code that fails checkstyle should be reformatted, no more no less.
- Line length should not be ignored / suppressed, but fixed. Looks like you added many suppressions for that. There should be none.


Once again I appreciate your effort, great job!
I believe this is gettin closer!

**Comment by damonxue** [comment]
* The reason for formatting too many files is to make sure that they all end with 'lf'.
* I will change too many 'lineLength'.

**Comment by damonxue** [comment]
1 #1069

**Pull request closed without merging**
