### PR TITLE
[SHIRO-683] Upgrade to spring-boot 1.5.19.RELEASE

### PR DESCRIPTION
**Pull request by fpapon**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/68/

**Comment by jbonofre** [comment]
Why not upgrading for spring-boot 2 ?

**Comment by fpapon** [comment]
@jbonofre Shiro 1.4.1 is still on Java 1.6, we will upgrade to 2.x on the next 1.5.0 (Java 8)

**Comment by fpapon** [comment]
@jbonofre I made update because of OWASP check

**Pull request merged**
