### PR TITLE
Include ISIS Security extensions to Shiro for RBAC and SSO

### PR DESCRIPTION
**Pull request by lucamilanesio**
The Apache ISIS project made a very interesting extension to Shiro
allowing the automatic fetch of LDAP Groups and assigning them 
to roles in order to resolve the user’s permissions.

This extension makes sense _inside_ Shiro as it can be reused in many
other context even outside ISIS.

Additionally I have extended the LDAP Realm and Authentication Filter
in order to allow SSO with an external authentication system resolved
through an HTTP Proxy (e.g. Kerberos, but it could be anything else, 
including commercial products such as Site-Minder) so that they can
be used in conjunction.

### CODE REVIEW

**Comment by bdemers** [comment]
The patch is: 
https://github.com/apache/shiro/pull/8/commits/91b5833a2ae88eafffc95ca33a264650eb053ec5

it doesn't render correctly after the switch from svn to git.

**Comment by fpapon** [comment]
@bdemers do you think this PR can be merged from the patch? May be we could create a new PR from the patch. Thoughts?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/55/

**Comment by bdemers** [comment]
@fpapon I don't think this change is generic enough to live in the Shiro repo.  There is probably some thing we could do on the Shiro side.

I'm not sure the Apache + GitHub integration lets us close issues either (other than opening an infra request or using a `Fixes: #8` trailer)

**Comment by bdemers** [comment]
Closing due to inactivity, please comment if you feel it should be reopened

**Pull request closed without merging**
