### PR TITLE
SHIRO-704 - Update Spring, Spring Boot + Hibernate

### PR DESCRIPTION
**Pull request by coheigea**
I tested the relevant samples.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/114/

**Comment by fpapon** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/115/

**Comment by fpapon** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/116/

**Pull request merged**
