### PR TITLE
Remove old JSTL jars

### PR DESCRIPTION
**Pull request by coheigea**
Remove old JSTL jars and replace with up-to-date Apache version, which doesn't have a CVE associated with it.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/137/

**Comment by bdemers** [comment]
Thanks again!

**Comment by fpapon** [comment]
@coheigea Thanks for the PR! 
I created a Jira for tracing : https://issues.apache.org/jira/browse/SHIRO-715

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/139/

**Pull request merged**
