### PR TITLE
Reduce shiro test logging level to INFO

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by bdemers** [comment]
@fpapon, related to your build cleanup PRs
I have mixed feelings about this, as generally I think extra logging is useful for CI, but in general I would typically just run the test locally and configure the logging i'd need at that point.

Thoughts?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/99/

**Comment by fpapon** [comment]
@bdemers full agree, we only have to put in `TRACE` or `DEBUG` when we have some errors and help to fix.

**Comment by fpapon** [comment]
@bdemers I think we should also put the root logger to `INFO` in the `samples/guice/src/main/resources/log4j.properties`

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/105/

**Pull request merged**
