### PR TITLE
org.apache.shiro.authz.AuthorizationException: Not authorized to invoke method:

### PR DESCRIPTION
**Pull request by zhuyouzhufu**
Can this exception be thrown？Because I want to customize the message。

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/126/

**Comment by bdemers** [comment]
Hey @zhuyouzhufu Thanks for the PR

It looks like you might have picked the wrong source/target branch though?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/127/

**Comment by fpapon** [comment]
@zhuyouzhufu you want to push on the `1.4.x` branch instead of `master` branch. It's better to make a PR on master.

**Comment by zhuyouzhufu** [comment]
thank you





------------------ 原始邮件 ------------------
发件人: "Fran&#xE7;ois Papon"<notifications@github.com>; 
发送时间: 2019年6月27日(星期四) 凌晨1:19
收件人: "apache/shiro"<shiro@noreply.github.com>; 
抄送: "樊松"<562167488@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [apache/shiro] org.apache.shiro.authz.AuthorizationException: Notauthorized to invoke method: (#155)




@zhuyouzhufu you want to push on the 1.4.x branch instead of master branch. It's better to make a PR on master.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/134/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/135/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/138/

**Comment by fpapon** [comment]
Hi @zhuyouzhufu, do you need some help to fix your branch issue? I can create a new PR based on yours if you want. Let me know ;)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/140/

**Comment by bdemers** [comment]
Closing for now.
@zhuyouzhufu, please open a new PR with your changes against master.
Thanks!

**Pull request closed without merging**
