### PR TITLE
Refactor: AssertJ best practices by @timtebeek

### PR DESCRIPTION
**Pull request by lprimak**
Introduce AssertJ by @timtebeek 
Supersedes #1450 and #1452

Following this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [GitHub issue](https://github.com/apache/shiro/issues) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a GitHub issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[#XXX] - Fixes bug in SessionManager`,
       where you replace `#XXX` with the appropriate GitHub issue. Best practice
       is to use the GitHub issue title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] add `fixes #XXX` if merging the PR should close a related issue.
 - [x] Run `mvn verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`. 
 - [x] Committers: Make sure a milestone is set on the PR
 
Trivial changes like typos do not require a GitHub issue (javadoc, comments...). 
In this case, just format the pull request title like `[DOC] - Add javadoc in SessionManager`.
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://github.com/apache/shiro/blob/master/CONTRIBUTING.md)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by lprimak — COMMENTED** [review]
Unfortunately, there are many warnings. See https://jenkins.hope.nyc.ny.us/job/docker-shiro-ci/job/main/38/analysis/

**Comment by lprimak** [comment]
Hi, @timtebeek 
Unfortunately, I had to revert the AssertJ refactor. There are 66 new warnings that have resulted from the compiler.

**Comment by timtebeek** [comment]
It seems 51 of those warnings are in `JndiLdapContextFactoryTest`, with cases like this one:
image

For comparison, this is what was there before, with `assertEquals` taking two objects as input:
image


What would you recommend we do about such instances?

**Comment by lprimak** [comment]
And once again, proper testing reveals underlying code issues :) working on it

**Comment by lprimak** [comment]
yay! It's green https://jenkins.hope.nyc.ny.us/job/docker-shiro-ci/job/assert-j-best-practices/1/

**Comment by lprimak** [comment]
Please pay special attention to this commit: https://github.com/apache/shiro/pull/1454/commits/798cd1851aaa5ba2bb39ad5f4dc664dd38d9b421

I believe this is safe to put into `2.0.1` version because the API doesn't really change and just the generics are made explicit.
What do you think?

**Comment by bmarwell** [comment]
> Please pay special attention to this commit: https://github.com/apache/shiro/pull/1454/commits/798cd1851aaa5ba2bb39ad5f4dc664dd38d9b421
> 
> I believe this is safe to put into `2.0.1` version because the API doesn't really change and just the generics are made explicit.
> What do you think?

Urgh. By definition a breaking change! Maybe put the 3.x label on that commit?

It's probably safe though

**Comment by lprimak** [comment]
My understanding of Java generics erasure is that this change is source and binary compatible with the previous... but I could be wrong.
In former case it would be safe to merge for 2.0.1 and latter it isn't :)

**Comment by bmarwell** [comment]
Binary: yes. 
Source compatible: most likely yes, but not if a user explicitly defined something else like Object,Object. Then no. 

I'd be okay with this one as it is early 2.0.x for that reason. 

@bdemers @fpapon Opinions?

**Comment by lprimak** [comment]
> but not if a user explicitly defined something else like Object,Object.

Since previous code was "raw" class without any parameters, they would have to cast in that case anyway...

**Comment by fpapon** [comment]
I think the problem can be this one about api change:

    public void setEnvironment(Map<String, Object> env) {

For now user can put any type in the key and we can imagine that he should use a String but we are not sure.

I understand the purpose of the best practice but it's not a good idea to update our api because of unit test framework change.

**Comment by bmarwell** [comment]
> I think the problem can be this one about api change:
> 
>     public void setEnvironment(Map<String, Object> env) {
> 
> For now user can put any type in the key and we can imagine that he should use a String but we are not sure.
> 
> I understand the purpose of the best practice but it's not a good idea to update our api because of unit test framework change.

Yes, that's a real no go and needs to wait until 3.

**Comment by lprimak** [comment]
Yup. As disappointing as this sounds, this one will have to wait

**Comment by bmarwell** [comment]
@lprimak just modify your branch to leave that one out and merge it into 2.0.1

Then do another for 3.0.0 with that change.

**Comment by bdemers** [comment]
Just catching up after some travel.

Would most of the concerns here go away if we created a custom assertion for `JndiLdapContextFactory` and `PrincipalCollection`?

That way we would at least get the migration to AssertJ in (thanks again @timtebeek).
And we can create an issue/TODO to cleanup the type <> everywhere.
Speaking of... is there an OpenRewrite recipe for that? 😄

**Comment by bdemers** [comment]
(I can volunteer to write the assertion class, if that resolves the issues), it would probably read something like:
```java
Shiro.assertThat(factory).containsEnvironment("foo, "bar");
```

**Comment by lprimak** [comment]
Yea, that sounds great! If there are no warnings it's all good by me :)

**Comment by lprimak** [comment]
I have reverted the API change commit.

**Comment by bdemers** [comment]
I started hacking a custom Assertion class up, and IMHO, it's too complex for the value it provides.

The value is essentially, working around a valid compiler warning.  The better solution for that is doing something like:
`@SuppressWarnings("unchecked")` to the relevant tests. We have a bunch of suppressions in the tests already.

My current plan is to open an issue to fix the generic type defs, and mark the effected test methods with something like:

```java
@SuppressWarning("unchecked") // TODO: Remove this warning when issue #xxxx is resolved
public void someTestMethod() {
    // ...
    assertThat(env).containsEntry(Context.SECURITY_PRINCIPAL, "foo");
    // ...
}
```

Any objections to this approach?

> [!NOTE]
> I do think custom assertion classes could be useful in other places, just in this case.

**Comment by lprimak** [comment]
No onjections from me.

**Pull request merged**
