### PR TITLE
Replace 'ACS' with 'Apache Shiro'

### PR DESCRIPTION
**Pull request by ankon**

### CODE REVIEW

**Comment by bdemers** [comment]
Thanks for noticing the find/replace errors from the original Apache Cloud Stack doc!

I just merged this, I found a couple more 'ACS' in there that I squashed in, it may take up to an hour to show up here.

**Comment by bdemers** [comment]
@ankon 
I cannot close this due to how this repo is configured as an apache mirror.

The only option to close it I have is to push a commit with 'close #11' in it.

**Comment by ankon** [comment]
Or I can close it. Thanks for merging :)

**Comment by bdemers** [comment]
Thanks!

**Pull request closed without merging**
