### PR TITLE
[SHIRO-669] Included a boolean flag in FirstSuccessfulStrategy to break after first successful authentication

### PR DESCRIPTION
**Pull request by ashokkumarta**
Included a boolean short circuit flag to indicate if FirstSuccessfulStrategy should break after the first successful authentication. By default this flag is false & continues to iterate through all realms.

### CODE REVIEW

**Comment by bdemers** [comment]
Hey @ashokkumarta I thought I or someone had responded to this already (and then the holiday's hit)

I like this, but I have a couple comments:
1.) rename `shortCircuitFlag` to something else. Maybe something like `stopAfterFirstSuccess` (naming things is the hardest part)
2.) Can you add a test for this?

**Comment by ashokkumarta** [comment]
@bdemers Agreed... Naming is everything:) Done and pushed those changes

**Comment by bdemers** [comment]
Great!

**Comment by fpapon** [comment]
@ashokkumarta can you rebase to resolve conflicts please? Thanks!

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/53/

**Comment by fpapon** [comment]
supercedes by https://github.com/apache/shiro/pull/184

**Pull request closed without merging**
