### PR TITLE
SHIRO-711 - Deprecate JavaEnvironment

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/128/

**Comment by coheigea** [comment]
@bdemers  Yes, done.

**Comment by bdemers** [comment]
Thanks!! 

Sorry one more nit, Can you add a `@deprecated` javadoc tag?  Maybe say something about will remove in the next major version? or this class is no longer used by Shiro 🤔 ?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/130/

**Comment by coheigea** [comment]
@bdemers Done

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/131/

**Comment by fpapon** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/136/

**Comment by fpapon** [comment]
Hi @bdemers, are you now ok to approve this PR?

**Comment by bdemers** [comment]
Thanks for catching that @fpapon, I thought I had already changed my vote

**Pull request merged**
