### PR TITLE
SHIRO-708 - Remove deprecated shiro-cas module

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/122/

**Comment by fpapon** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/123/

**Comment by bdemers** [comment]
We need to think about how we message this.  If the next version is 1.5 and we remove a module that is a breaking change at a high level. But not at an actual code level.
🤔

**Comment by fpapon** [comment]
@bdemers the module is deprecated in the current website page `https://shiro.apache.org/cas.html`.
Do you think it's good to remove it?

**Comment by fpapon** [comment]
@bdemers We are moving now on 2.0.0, I think we could remove this module.
Thoughts?

**Comment by bdemers** [comment]
@fpapon absolutely! 🗑️

**Comment by fpapon** [comment]
@coheigea can you rebase and resolve the conflicting files please?

**Comment by coheigea** [comment]
@fpapon  Done

**Pull request merged**
