### PR TITLE
1.x

### PR DESCRIPTION
**Pull request by rainbowJson**
SimpleCookie get cookie failed,when I set cookie to root,but in sub path exists the sample cookieId,
shiro get invaid cookie。eg:
www.domain.com/    cookie one
www.domain.com/abc    cookie two
-----------------------------------------

```java
private static javax.servlet.http.Cookie getCookie(HttpServletRequest request, String cookieName) {
        javax.servlet.http.Cookie cookies[] = request.getCookies();
      javax.servlet.http.Cookie cookie = null;
        if (cookies != null) {
            for (javax.servlet.http.Cookie cookie : cookies) {
                if (cookie.getName().equals(cookieName)) {
                    cookie = cookie;
                }
            }
        }
        return cookie;
    }
```

### CODE REVIEW

**Comment by bdemers** [comment]
@rainbowJson was this PR targeted to the correct branch?

**Comment by rainbowJson** [comment]
i found in 1.3.x-1.4.0 @bdemers

**Comment by bdemers** [comment]
@rainbowJson I'm not sure i'm following.  There are many conflicts in this PR

**Comment by fpapon** [comment]
@rainbowJson Can you rebase with master to resolved the conflicts?

**Comment by bmhm** [comment]
Hello @rainbowJson.

I will close this PR for now. There are too many conflicts, and the description is not clear enough what the intended  change is.

Feel free to open an issue or another pull request if the underlying problem you wanted to solve still exists.

**Pull request closed without merging**
