### PR TITLE
[SHIRO-717] Upgrade to maven-pmd-plugin 3.12.0

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @fpapon

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Shiro-pr/149/<h2>Build result: ABORTED</span></h2>[...truncated 14.46 MB...][INFO] --- buildnumber-maven-plugin:1.4:create (default) @ shiro-test-coverage ---[INFO] Executing: /bin/sh -c cd '/home/jenkins/jenkins-slave/workspace/Shiro-pr/test-coverage' && 'git' 'rev-parse' '--verify' 'HEAD'[INFO] Working directory: /home/jenkins/jenkins-slave/workspace/Shiro-pr/test-coverage[INFO] Storing buildNumber: 7bf15d5b3d8f8ee3ca535a972d20f9885b8e9a2e at timestamp: 1563994309638[WARNING] Cannot get the branch information from the git repository: Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref[INFO] Executing: /bin/sh -c cd '/home/jenkins/jenkins-slave/workspace/Shiro-pr/test-coverage' && 'git' 'rev-parse' '--verify' 'HEAD'[INFO] Working directory: /home/jenkins/jenkins-slave/workspace/Shiro-pr/test-coverage[INFO] Storing buildScmBranch: UNKNOWN[INFO] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ shiro-test-coverage ---[INFO] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ shiro-test-coverage ---[INFO] [INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles) @ shiro-test-coverage ---[INFO] [INFO] --- jacoco-maven-plugin:0.8.4:merge (jacoco-it-merge) @ shiro-test-coverage ---Build timed out (after 240 minutes). Marking the build as aborted.Build was abortedchannel stoppedSetting status of dd853ce9601c678bf239b5d2148700a8626097f6 to FAILURE with url https://builds.apache.org/job/Shiro-pr/149/ and message: 'FAILURE 'Using context: Jenkins: mvn clean install

**Comment by fpapon** [comment]
retest this please

**Comment by fpapon** [comment]
retest this please

**Comment by fpapon** [comment]
There is a test error on the build but for me it's not related to this PR.
https://builds.apache.org/job/Shiro-pr/org.apache.shiro.samples$samples-web/153/testReport/junit/org.apache.shiro.test/ContainerIntegrationIT/logIn/
@bdemers are you ok?

**Pull request merged**
